name: Dice Finoana

on:
  workflow_dispatch:
    inputs:
      accountFile:
        description: "account_xxx_tronpick_email.json"
        required: true
      baseBet:
        description: "Mise initiale (0 = auto solde/2000)"
        required: false
        default: "0"

jobs:
  dice:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
      image: ghcr.io/hasiniainahasina1-art/camoufox-system:latest
      options: --user camoxuser
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Cloner pick-faucet
        run: |
          git clone --depth=1 --branch main \
            https://${{ secrets.GH_TOKEN }}@github.com/hasiniainahasina1-art/pick-faucet.git /tmp/repo
          cp -rn /tmp/repo/. /app/
          rm -rf /tmp/repo

      - name: Lancer dice
        working-directory: /app
        env:
          HOME: /home/camoxuser
          DISPLAY: ":99"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: hasiniainahasina1-art
          GH_REPO: pick-faucet
          GH_BRANCH: main
          CRYPTO_SECRET: ${{ secrets.CRYPTO_SECRET }}
          ACCOUNT_FILE: ${{ github.event.inputs.accountFile }}
          BASE_BET: ${{ github.event.inputs.baseBet }}
        run: |
          timeout 7000 xvfb-run -s "-screen 0 1280x720x24" --auto-servernum \
            python dice_finoana.py
